### ISSUE TITLE
Docker build failed with exit code 1

### ISSUE THREAD

**Issue by AlexeyKorshun** [moatazeldebsy/Appium-Server-GitHub-Action#3]
**Describe the bug**
try to use action on CI and have an error "Docker build failed with exit code 1"

**Access to the following pieces of information (if you can):**
`Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

```
name: publish

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install and Run Appium Server
      uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
```
