### ISSUE TITLE
Error: Docker build failed with exit code 1

### ISSUE THREAD

**Issue by QA1980** [moatazeldebsy/Appium-Server-GitHub-Action#9]
I have tried to build CI Appium using  this yml action 
```
name: Appium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install and Run Appium Server
      uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4


```
Actual result : I get Docker build failed and Node version 11.x deprecation warning even using higher version 
================================================================================
  ================================================================================
  
                              ```
  DEPRECATION WARNING                            
  
    Node.js 11.x is no longer actively supported!
  
    You will not receive security or critical stability updates for this version.
  
    You should migrate to a supported version of Node.js as soon as possible.
    Use the installation script that corresponds to the version of Node.js you
    wish to install. e.g.
  
     * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium"
     * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium" (recommended)
     * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium"
     * https://deb.nodesource.com/setup_15.x — Node.js 15 "Fifteen"
  
    Please see https://github.com/nodejs/Release for details about which
    version may be appropriate for you.
  
    The NodeSource Node.js distributions repository contains
    information both about supported versions of Node.js and supported Linux
    distributions. To learn more about usage, see the repository:
      https://github.com/nodesource/distributions

```
